//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DwellingRepository.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatLocation
    {
        public CatLocation()
        {
            this.DwellingRel = new HashSet<DwellingRel>();
        }
    
        public int LocationId { get; set; }
        public int MunicipalityId { get; set; }
        public string Name { get; set; }
        public string Abbreviation { get; set; }
        public string Description { get; set; }
        public string ZipCode { get; set; }
    
        public virtual CatMunicipality CatMunicipality { get; set; }
        public virtual ICollection<DwellingRel> DwellingRel { get; set; }
    }
}
