//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DwellingRepository.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatMunicipality
    {
        public CatMunicipality()
        {
            this.CatLocation = new HashSet<CatLocation>();
        }
    
        public int MunicipalityId { get; set; }
        public int StateId { get; set; }
        public string Name { get; set; }
        public string Abbreviation { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<CatLocation> CatLocation { get; set; }
        public virtual CatState CatState { get; set; }
    }
}
