//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DwellingRepository.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DwellingHouse
    {
        public int DwellingHouseId { get; set; }
        public int DwellingId { get; set; }
        public int StreetId { get; set; }
        public string OuterNumber { get; set; }
        public bool IsObsolete { get; set; }
    
        public virtual DwellingRel DwellingRel { get; set; }
        public virtual Street Street { get; set; }
    }
}
