//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DwellingRepository.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DwellingLocation
    {
        public int DwellingLocationId { get; set; }
        public int DwellingId { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Area { get; set; }
        public string Color { get; set; }
        public byte[] BuildingImage { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Coordinates { get; set; }
        public string Floor { get; set; }
    
        public virtual DwellingRel DwellingRel { get; set; }
    }
}
