//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DwellingRepository.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DwellingApartment
    {
        public int DwellingApartmentId { get; set; }
        public int DwellingId { get; set; }
        public int BuildingId { get; set; }
        public string InnerNumber { get; set; }
        public string Floor { get; set; }
        public bool IsObsolete { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual DwellingRel DwellingRel { get; set; }
    }
}
