//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DwellingRepository.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Periodicity
    {
        public Periodicity()
        {
            this.Service = new HashSet<Service>();
        }
    
        public int PeriodicityId { get; set; }
        public string Name { get; set; }
        public int Value { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<Service> Service { get; set; }
    }
}
