//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DwellingRepository.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resident
    {
        public Resident()
        {
            this.DwellingResidentRel = new HashSet<DwellingResidentRel>();
        }
    
        public int ResidentId { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Email2 { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string MobileNumber2 { get; set; }
        public string OfficeNumber { get; set; }
        public Nullable<int> DocumentTypeId { get; set; }
        public string DocumentNumber { get; set; }
        public string Image { get; set; }
        public bool Gender { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string Comments { get; set; }
        public bool IsObsolete { get; set; }
    
        public virtual DocumentType DocumentType { get; set; }
        public virtual ICollection<DwellingResidentRel> DwellingResidentRel { get; set; }
    }
}
