//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DwellingRepository.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.TaxServiceRel = new HashSet<TaxServiceRel>();
        }
    
        public int ServiceId { get; set; }
        public string Name { get; set; }
        public decimal Value { get; set; }
        public System.DateTime PeriodStart { get; set; }
        public Nullable<System.DateTime> PeriodEnd { get; set; }
        public int PeriodicityId { get; set; }
        public int DaysToPay { get; set; }
        public int DaysExtension { get; set; }
        public string Comments { get; set; }
        public bool IsActive { get; set; }
        public bool IsObsolete { get; set; }
    
        public virtual Periodicity Periodicity { get; set; }
        public virtual ICollection<TaxServiceRel> TaxServiceRel { get; set; }
    }
}
