//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DwellingSystemUi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResAddressRep {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResAddressRep() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DwellingSystemUi.Resources.ResAddressRep", typeof(ResAddressRep).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Ext..
        /// </summary>
        public static string FIELD_EXTNUM {
            get {
                return ResourceManager.GetString("FIELD_EXTNUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Int..
        /// </summary>
        public static string FIELD_INTNUM {
            get {
                return ResourceManager.GetString("FIELD_INTNUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonia.
        /// </summary>
        public static string FIELD_LOCATION {
            get {
                return ResourceManager.GetString("FIELD_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipio.
        /// </summary>
        public static string FIELD_MUNICIPALITY {
            get {
                return ResourceManager.GetString("FIELD_MUNICIPALITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string FIELD_PHONE {
            get {
                return ResourceManager.GetString("FIELD_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string FIELD_STATE {
            get {
                return ResourceManager.GetString("FIELD_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calle.
        /// </summary>
        public static string FIELD_STREET {
            get {
                return ResourceManager.GetString("FIELD_STREET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código postal.
        /// </summary>
        public static string FIELD_ZIPCODE {
            get {
                return ResourceManager.GetString("FIELD_ZIPCODE", resourceCulture);
            }
        }
    }
}
