//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DwellingRepository.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResManagment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResManagment() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DwellingRepository.Resources.ResManagment", typeof(ResManagment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        public static string ADDRESS_LABEL {
            get {
                return ResourceManager.GetString("ADDRESS_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departamento.
        /// </summary>
        public static string APARMENT_LABEL {
            get {
                return ResourceManager.GetString("APARMENT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edificio.
        /// </summary>
        public static string BUILDING_LABEL {
            get {
                return ResourceManager.GetString("BUILDING_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de documento.
        /// </summary>
        public static string DOCUMENT_TYPE_LABEL {
            get {
                return ResourceManager.GetString("DOCUMENT_TYPE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel.
        /// </summary>
        public static string FLOOR_LABEL {
            get {
                return ResourceManager.GetString("FLOOR_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Femenino.
        /// </summary>
        public static string GENDER_FEMALE_LABEL {
            get {
                return ResourceManager.GetString("GENDER_FEMALE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Género.
        /// </summary>
        public static string GENDER_LABEL {
            get {
                return ResourceManager.GetString("GENDER_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masculino.
        /// </summary>
        public static string GENDER_MALE_LABEL {
            get {
                return ResourceManager.GetString("GENDER_MALE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casa.
        /// </summary>
        public static string HOUSE_LABEL {
            get {
                return ResourceManager.GetString("HOUSE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero interior.
        /// </summary>
        public static string INNER_NUMBER_LABEL {
            get {
                return ResourceManager.GetString("INNER_NUMBER_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido(s).
        /// </summary>
        public static string LASTNAME_LABEL {
            get {
                return ResourceManager.GetString("LASTNAME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonia.
        /// </summary>
        public static string LOCATION_LABEL {
            get {
                return ResourceManager.GetString("LOCATION_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipio.
        /// </summary>
        public static string MUNICIPALITY_LABEL {
            get {
                return ResourceManager.GetString("MUNICIPALITY_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string NAME_LABEL {
            get {
                return ResourceManager.GetString("NAME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre(s).
        /// </summary>
        public static string NAMES_LABEL {
            get {
                return ResourceManager.GetString("NAMES_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número exterior.
        /// </summary>
        public static string OUTER_NUMBER_LABEL {
            get {
                return ResourceManager.GetString("OUTER_NUMBER_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos del residente.
        /// </summary>
        public static string RESIDENT_DATA_LABEL {
            get {
                return ResourceManager.GetString("RESIDENT_DATA_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residente.
        /// </summary>
        public static string RESIDENT_LABEL {
            get {
                return ResourceManager.GetString("RESIDENT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string STATE_LABEL {
            get {
                return ResourceManager.GetString("STATE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción de calle.
        /// </summary>
        public static string STREET_DESCRIPTION_LABEL {
            get {
                return ResourceManager.GetString("STREET_DESCRIPTION_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calle.
        /// </summary>
        public static string STREET_LABEL {
            get {
                return ResourceManager.GetString("STREET_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código postal.
        /// </summary>
        public static string ZIPCODE_LABEL {
            get {
                return ResourceManager.GetString("ZIPCODE_LABEL", resourceCulture);
            }
        }
    }
}
